In [121]:
import numpy as np 
import pandas as pd
import matplotlib
import glob

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/qp/mnlhrt5x2rx27zstwr3s8_200000gp/T/ipykernel_64696/1963750700.py", line 3, in <module>
    import matplotlib
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: initialization failed

In [80]:

files = glob.glob("youtube-dataset/*.csv")
print(files)

['youtube-dataset/Youtube03.csv', 'youtube-dataset/Youtube02.csv', 'youtube-dataset/Youtube01.csv', 'youtube-dataset/Youtube05.csv', 'youtube-dataset/Youtube04.csv']

In [81]:
lista = []
for i in files:
    lista.append(pd.read_csv(i))

In [82]:
lista[0]

,COMMENT_ID,AUTHOR,DATE,CONTENT,CLASS
0,z13uwn2heqndtr5g304ccv5j5kqqzxjadmc0k,Corey Wilson,2015-05-28T21:39:52.376000,"<a href=""http://www.youtube.com/watch?v=KQ6zr6...",0
1,z124jvczaz3dxhnbc04cffk43oiugj25yzo0k,Epic Gaming,2015-05-28T20:07:20.610000,wierd but funny﻿,0
2,z13tczjy5xj0vjmu5231unho1ofey5zdk,LaS Music,2015-05-28T19:23:35.355000,"Hey guys, I&#39;m a human.<br /><br /><br />Bu...",1
3,z13tzr0hdpnayhqqc04cd3zqqqjkf3ngckk0k,Cheryl Fox,2015-05-28T17:49:35.294000,Party Rock....lol...who wants to shuffle!!!﻿,0
4,z12pcvix4zedcjvyb04ccr1r0mr2g5xwyng0k,PATRICK_TW,2015-05-28T16:28:26.818000,Party rock﻿,0
...,...,...,...,...,...
433,z13lvr4iupatjlrem231yvpxolzvspwdl,Salty Croc,2014-07-22T04:20:37.489000,Like this comment for no reason﻿,1
434,z12lxhrqdkyusbkji04cihtrvn3jvxnqszg0k,Bob Orton,2014-07-22T00:26:50.820000,love this song﻿,0
435,z12xhdjrsxm3v550w22oynsjrnmvjhkvj,LuckyMusiqLive,2014-07-21T22:25:54.048000,this song is awesome. these guys are the best....,1
436,z13msngo3qvwx1ym223pehqgouexzdmnm,xXxPWND 420xXx,2014-07-21T11:05:51.945000,HOW MANY THUMBS UP FOR LOUIS SAVING THE DAY!?!?﻿,1
437,z120hptrylzqzdsoj04cepaonmuyyr1afj0,Matheus Macedo,2014-07-21T04:24:24.585000,NICE :3﻿,0

In [83]:
df = pd.concat(lista ,ignore_index=True)

In [84]:
df

,COMMENT_ID,AUTHOR,DATE,CONTENT,CLASS
0,z13uwn2heqndtr5g304ccv5j5kqqzxjadmc0k,Corey Wilson,2015-05-28T21:39:52.376000,"<a href=""http://www.youtube.com/watch?v=KQ6zr6...",0
1,z124jvczaz3dxhnbc04cffk43oiugj25yzo0k,Epic Gaming,2015-05-28T20:07:20.610000,wierd but funny﻿,0
2,z13tczjy5xj0vjmu5231unho1ofey5zdk,LaS Music,2015-05-28T19:23:35.355000,"Hey guys, I&#39;m a human.<br /><br /><br />Bu...",1
3,z13tzr0hdpnayhqqc04cd3zqqqjkf3ngckk0k,Cheryl Fox,2015-05-28T17:49:35.294000,Party Rock....lol...who wants to shuffle!!!﻿,0
4,z12pcvix4zedcjvyb04ccr1r0mr2g5xwyng0k,PATRICK_TW,2015-05-28T16:28:26.818000,Party rock﻿,0
...,...,...,...,...,...
1950,LneaDw26bFu3RCmyrWyP9S6wh1h9dBv3X95g1HzKAb4,Dany PK,NaN,SUBSCRIBE TO MY CHANNEL X PLEASE!. SPARE,1
1951,LneaDw26bFsD65dtIvAEObWYIYnFTqQDKBek_Ypz3J8,SmexyFriedChicken,NaN,Check out my videos guy! :) Hope you guys had ...,1
1952,LneaDw26bFuvs-8oWkLpAFa6g3QHpWD8k7sbbMP3Bg8,The Guy That's Done Everything,NaN,3 yrs ago I had a health scare but thankfully ...,1
1953,z12hfp2wmyuqztkw504cgblyxtbsxjuzeow0k,Jesse Pinkman,2015-05-06T11:42:44.601000,Rihanna looks so beautiful with red hair ;)﻿,0
1954,z13tsbc5vvn0hdozz04chjt51lq1cvris0k,Gaming Gaming,2015-05-06T10:56:35.972000,857.482.940 views AWESOME !!!!!!!!!!!!!!!!!!!!...,0

In [85]:
df.shape

(1955, 5)

In [86]:
df.columns

Index(['COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT', 'CLASS'], dtype='str')

In [87]:
df.drop(['COMMENT_ID', 'AUTHOR', 'DATE'] , axis=1 , inplace=True)

In [88]:
df.head()

                                             CONTENT  CLASS
0  <a href="http://www.youtube.com/watch?v=KQ6zr6...      0
1                                   wierd but funny﻿      0
2  Hey guys, I&#39;m a human.<br /><br /><br />Bu...      1
3       Party Rock....lol...who wants to shuffle!!!﻿      0
4                                        Party rock﻿      0

In [89]:
df.describe()

             CLASS
count  1955.000000
mean      0.513555
std       0.499944
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [90]:
df.describe(include='object')

/var/folders/qp/mnlhrt5x2rx27zstwr3s8_200000gp/T/ipykernel_64696/87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

                                  CONTENT
count                                1955
unique                               1759
top     Check out this video on YouTube:﻿
freq                                   97

In [91]:
df.isna().sum()

CONTENT    0
CLASS      0
dtype: int64

In [92]:
df.duplicated().sum()

np.int64(196)

In [93]:
df =df.drop_duplicates()

In [94]:
df.duplicated().sum()

np.int64(0)

In [95]:
df['CLASS'] .value_counts()

CLASS
0    919
1    840
Name: count, dtype: int64

In [96]:
X = df['CONTENT']
Y = df['CLASS']

In [97]:
from sklearn.model_selection import train_test_split

In [103]:
X_train,X_test,Y_train_,Y_test = train_test_split(X,Y , test_size=0.2, random_state=42)

In [104]:
from sklearn.feature_extraction.text import CountVectorizer

In [105]:
Vectorizer = CountVectorizer()

In [106]:
X_train = Vectorizer.fit_transform(X_train)
X_test = Vectorizer.transform(X_test)

In [107]:
X_train.shape

(1407, 3759)

In [110]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1407, 3759))

In [111]:
from sklearn.naive_bayes import MultinomialNB

In [112]:
NB = MultinomialNB()

In [114]:
NB.fit(X_train,Y_train_)

MultinomialNB()

In [115]:
NB.get_params()

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True, 'force_alpha': True}

In [116]:
NB.feature_count_[0]

array([ 2., 25.,  1., ...,  1.,  1.,  1.], shape=(3759,))

In [117]:
from sklearn.metrics import ConfusionMatrixDisplay, recall_score,precision_score

In [118]:
y_pred = NB.predict(X_test)

In [120]:
ConfusionMatrixDisplay.from_predictions ( Y_test , y_pred )

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/qp/mnlhrt5x2rx27zstwr3s8_200000gp/T/ipykernel_64696/2348329269.py", line 1, in <module>
    ConfusionMatrixDisplay.from_predictions ( Y_test , y_pred )
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_plot/confusion_matrix.py", line 472, in from_predictions
    check_matplotlib_support(f"{cls.__name__}.from_predictions")
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/sklearn/utils/_optional_dependencies.py", line 17, in check_matplotlib_support
    import matplotlib  # noqa: F401
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/ticker.py", line 144, in <module>
    from matplotlib import transforms as mtransforms
  File "/Users/khaledayman/Desktop/main/workspace/pythonFiles/anaconda3/lib/python3.12/site-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.5.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: ConfusionMatrixDisplay.from_predictions requires matplotlib. You can install matplotlib with `pip install matplotlib`